// ─────────────────────────────────────────────────────────────────
// Achievement data & helpers — separated to allow React Fast Refresh
// ─────────────────────────────────────────────────────────────────

export const BADGE_DEFINITIONS = [
  // ── Streak Badges
  {
    id: "streak_3",
    category: "consistency",
    emoji: "🔥",
    name: "Ignition",
    tagline: "3-day streak",
    howToEarn: "Study 3 days in a row — don't break the chain!",
    condition: (s) => s.currentStreak >= 3,
    progress: (s) => Math.min(100, Math.round((s.currentStreak / 3) * 100)),
    progressLabel: (s) => `${s.currentStreak}/3 days`,
    xp: 50,
    color: "#FF6B35",
    bg: "#FFF3EE",
    border: "#FFD4C2",
    gradient: "linear-gradient(135deg, #FF6B35, #FF4500)",
  },
  {
    id: "streak_7",
    category: "consistency",
    emoji: "⚡",
    name: "On Fire",
    tagline: "7-day streak",
    howToEarn: "Complete at least 1 assessment every day for 7 days straight.",
    condition: (s) => s.currentStreak >= 7,
    progress: (s) => Math.min(100, Math.round((s.currentStreak / 7) * 100)),
    progressLabel: (s) => `${s.currentStreak}/7 days`,
    xp: 150,
    color: "#E85A00",
    bg: "#FFF1E6",
    border: "#FFCBA4",
    gradient: "linear-gradient(135deg, #E85A00, #C44000)",
  },
  {
    id: "streak_14",
    category: "consistency",
    emoji: "🌟",
    name: "Unstoppable",
    tagline: "14-day streak",
    howToEarn: "Keep your streak alive for 2 full weeks. You've got this!",
    condition: (s) => s.currentStreak >= 14,
    progress: (s) => Math.min(100, Math.round((s.currentStreak / 14) * 100)),
    progressLabel: (s) => `${s.currentStreak}/14 days`,
    xp: 300,
    color: "#C4952A",
    bg: "#FFF9E6",
    border: "#FFE9A0",
    gradient: "linear-gradient(135deg, #E8C547, #C4952A)",
  },
  {
    id: "streak_30",
    category: "consistency",
    emoji: "👑",
    name: "Legend",
    tagline: "30-day streak",
    howToEarn: "Study every single day for a full month. Truly legendary!",
    condition: (s) => s.currentStreak >= 30,
    progress: (s) => Math.min(100, Math.round((s.currentStreak / 30) * 100)),
    progressLabel: (s) => `${s.currentStreak}/30 days`,
    xp: 750,
    color: "#9B6F00",
    bg: "#FFF7E0",
    border: "#FFE08A",
    gradient: "linear-gradient(135deg, #C4952A, #9B6F00)",
  },
  // ── Milestone Badges
  {
    id: "first_assessment",
    category: "milestone",
    emoji: "🚀",
    name: "First Step",
    tagline: "1st assessment done",
    howToEarn: "Complete your very first assessment — the journey begins here!",
    condition: (s) => s.totalAssessments >= 1,
    progress: (s) => Math.min(100, s.totalAssessments >= 1 ? 100 : 0),
    progressLabel: (s) => `${Math.min(s.totalAssessments, 1)}/1 assessment`,
    xp: 25,
    color: "#7C3AED",
    bg: "#F5F0FF",
    border: "#D8C4FF",
    gradient: "linear-gradient(135deg, #7C3AED, #5B21B6)",
  },
  {
    id: "assessments_5",
    category: "milestone",
    emoji: "📚",
    name: "Bookworm",
    tagline: "5 assessments completed",
    howToEarn: "Finish any 5 assessments. Mix topics to learn more!",
    condition: (s) => s.totalAssessments >= 5,
    progress: (s) => Math.min(100, Math.round((s.totalAssessments / 5) * 100)),
    progressLabel: (s) => `${Math.min(s.totalAssessments, 5)}/5 assessments`,
    xp: 100,
    color: "#2563EB",
    bg: "#EFF6FF",
    border: "#BFDBFE",
    gradient: "linear-gradient(135deg, #2563EB, #1D4ED8)",
  },
  {
    id: "assessments_10",
    category: "milestone",
    emoji: "🎯",
    name: "Dedicated",
    tagline: "10 assessments completed",
    howToEarn: "Complete 10 assessments — you're building a real habit!",
    condition: (s) => s.totalAssessments >= 10,
    progress: (s) => Math.min(100, Math.round((s.totalAssessments / 10) * 100)),
    progressLabel: (s) => `${Math.min(s.totalAssessments, 10)}/10 assessments`,
    xp: 200,
    color: "#059669",
    bg: "#ECFDF5",
    border: "#A7F3D0",
    gradient: "linear-gradient(135deg, #059669, #047857)",
  },
  {
    id: "assessments_25",
    category: "milestone",
    emoji: "🏅",
    name: "Knowledge Seeker",
    tagline: "25 assessments completed",
    howToEarn: "Reach 25 total assessments. A true seeker of knowledge!",
    condition: (s) => s.totalAssessments >= 25,
    progress: (s) => Math.min(100, Math.round((s.totalAssessments / 25) * 100)),
    progressLabel: (s) => `${Math.min(s.totalAssessments, 25)}/25 assessments`,
    xp: 400,
    color: "#1B332C",
    bg: "#ECFDF5",
    border: "#6EE7B7",
    gradient: "linear-gradient(135deg, #1B332C, #065F46)",
  },
  {
    id: "assessments_50",
    category: "milestone",
    emoji: "🌟",
    name: "Grand Master",
    tagline: "50 assessments completed",
    howToEarn: "Complete 50 assessments. You are among the very best!",
    condition: (s) => s.totalAssessments >= 50,
    progress: (s) => Math.min(100, Math.round((s.totalAssessments / 50) * 100)),
    progressLabel: (s) => `${Math.min(s.totalAssessments, 50)}/50 assessments`,
    xp: 1000,
    color: "#C4952A",
    bg: "#FFF9E6",
    border: "#FFE9A0",
    gradient: "linear-gradient(135deg, #C4952A, #92400E)",
  },
  // ── Performance Badges
  {
    id: "perfect_score",
    category: "performance",
    emoji: "💯",
    name: "Perfectionist",
    tagline: "Score 100% on an assessment",
    howToEarn: "Get every single answer correct in one assessment. Aim for perfection!",
    condition: (s) => s.hasPerfectScore,
    progress: (s) => Math.min(100, Math.round(s.highestScore || 0)),
    progressLabel: (s) => `Best: ${s.highestScore || 0}%`,
    xp: 300,
    color: "#DC2626",
    bg: "#FEF2F2",
    border: "#FECACA",
    gradient: "linear-gradient(135deg, #DC2626, #991B1B)",
  },
  {
    id: "avg_80",
    category: "performance",
    emoji: "⭐",
    name: "High Achiever",
    tagline: "Average score 80%+",
    howToEarn: "Maintain an average score of 80% or higher across 3+ assessments.",
    condition: (s) => s.avgScore >= 80 && s.totalAssessments >= 3,
    progress: (s) => Math.min(100, Math.round((s.avgScore / 80) * 100)),
    progressLabel: (s) => `Avg: ${s.avgScore}% / 80%`,
    xp: 200,
    color: "#D97706",
    bg: "#FFFBEB",
    border: "#FDE68A",
    gradient: "linear-gradient(135deg, #D97706, #B45309)",
  },
  {
    id: "avg_90",
    category: "performance",
    emoji: "🏆",
    name: "Excellence",
    tagline: "Average score 90%+",
    howToEarn: "Achieve a 90%+ average across 5+ assessments. True excellence!",
    condition: (s) => s.avgScore >= 90 && s.totalAssessments >= 5,
    progress: (s) => Math.min(100, Math.round((s.avgScore / 90) * 100)),
    progressLabel: (s) => `Avg: ${s.avgScore}% / 90%`,
    xp: 500,
    color: "#C4952A",
    bg: "#FFF9E6",
    border: "#FFE9A0",
    gradient: "linear-gradient(135deg, #E8C547, #C4952A)",
  },
  // ── Improvement Badges
  {
    id: "improver_10",
    category: "improvement",
    emoji: "📈",
    name: "Rising Star",
    tagline: "Improved by 10%+ in a topic",
    howToEarn: "Improve your score by 10% or more in any subject area.",
    condition: (s) => s.maxImprovement >= 10,
    progress: (s) => Math.min(100, Math.round((s.maxImprovement / 10) * 100)),
    progressLabel: (s) => `Best improvement: +${Math.round(s.maxImprovement)}%`,
    xp: 150,
    color: "#0891B2",
    bg: "#ECFEFF",
    border: "#A5F3FC",
    gradient: "linear-gradient(135deg, #0891B2, #0E7490)",
  },
  {
    id: "improver_25",
    category: "improvement",
    emoji: "🚀",
    name: "Breakthrough",
    tagline: "Improved by 25%+ in a topic",
    howToEarn: "Achieve a 25% or more score improvement in any subject. Keep pushing!",
    condition: (s) => s.maxImprovement >= 25,
    progress: (s) => Math.min(100, Math.round((s.maxImprovement / 25) * 100)),
    progressLabel: (s) => `Best improvement: +${Math.round(s.maxImprovement)}%`,
    xp: 350,
    color: "#7C3AED",
    bg: "#F5F0FF",
    border: "#D8C4FF",
    gradient: "linear-gradient(135deg, #7C3AED, #5B21B6)",
  },
  // ── Consistency Badges
  {
    id: "active_5_days",
    category: "consistency",
    emoji: "📅",
    name: "Regular",
    tagline: "Active on 5 different days",
    howToEarn: "Complete at least one assessment on 5 separate calendar days.",
    condition: (s) => s.activeDays >= 5,
    progress: (s) => Math.min(100, Math.round((s.activeDays / 5) * 100)),
    progressLabel: (s) => `${Math.min(s.activeDays, 5)}/5 days`,
    xp: 100,
    color: "#16A34A",
    bg: "#F0FDF4",
    border: "#BBF7D0",
    gradient: "linear-gradient(135deg, #16A34A, #15803D)",
  },
  {
    id: "active_15_days",
    category: "consistency",
    emoji: "🗓️",
    name: "Habit Former",
    tagline: "Active on 15 different days",
    howToEarn: "Be active on 15 separate days. Learning is a habit, not a one-time event!",
    condition: (s) => s.activeDays >= 15,
    progress: (s) => Math.min(100, Math.round((s.activeDays / 15) * 100)),
    progressLabel: (s) => `${Math.min(s.activeDays, 15)}/15 days`,
    xp: 250,
    color: "#059669",
    bg: "#ECFDF5",
    border: "#A7F3D0",
    gradient: "linear-gradient(135deg, #059669, #047857)",
  },
  // ── Question Count
  {
    id: "questions_100",
    category: "milestone",
    emoji: "❓",
    name: "Question Crusher",
    tagline: "100 questions answered",
    howToEarn: "Answer a total of 100 questions across all your assessments.",
    condition: (s) => s.totalQuestions >= 100,
    progress: (s) => Math.min(100, Math.round((s.totalQuestions / 100) * 100)),
    progressLabel: (s) => `${Math.min(s.totalQuestions, 100)}/100 questions`,
    xp: 175,
    color: "#7C3AED",
    bg: "#F5F0FF",
    border: "#D8C4FF",
    gradient: "linear-gradient(135deg, #7C3AED, #5B21B6)",
  },
  {
    id: "questions_500",
    category: "milestone",
    emoji: "🧠",
    name: "Brain Power",
    tagline: "500 questions answered",
    howToEarn: "Answer 500 total questions. Your brain is getting sharper every day!",
    condition: (s) => s.totalQuestions >= 500,
    progress: (s) => Math.min(100, Math.round((s.totalQuestions / 500) * 100)),
    progressLabel: (s) => `${Math.min(s.totalQuestions, 500)}/500 questions`,
    xp: 600,
    color: "#C4952A",
    bg: "#FFF9E6",
    border: "#FFE9A0",
    gradient: "linear-gradient(135deg, #C4952A, #92400E)",
  },
];

export const CERTIFICATE_DEFINITIONS = [
  {
    id: "cert_beginner",
    name: "Beginner Achiever",
    subtitle: "Assessment Fundamentals",
    description: "Awarded for completing your first 5 assessments and establishing a learning habit.",
    condition: (s) => s.totalAssessments >= 5,
    progressDesc: (s) => `Complete ${Math.max(0, 5 - s.totalAssessments)} more assessments`,
    color: "#059669",
    gradient: "linear-gradient(135deg, #059669 0%, #065F46 100%)",
    emoji: "🎓",
    requiredBadges: ["first_assessment", "assessments_5"],
  },
  {
    id: "cert_consistent",
    name: "Consistency Champion",
    subtitle: "Dedication & Discipline",
    description: "Awarded for maintaining a 7-day streak and completing 10+ assessments.",
    condition: (s) => s.currentStreak >= 7 && s.totalAssessments >= 10,
    progressDesc: (s) => {
      const parts = [];
      if (s.currentStreak < 7) parts.push(`${7 - s.currentStreak} more streak days`);
      if (s.totalAssessments < 10) parts.push(`${10 - s.totalAssessments} more assessments`);
      return parts.length ? `Need: ${parts.join(" & ")}` : "Earned!";
    },
    color: "#2563EB",
    gradient: "linear-gradient(135deg, #2563EB 0%, #1E40AF 100%)",
    emoji: "🏅",
    requiredBadges: ["streak_7", "assessments_10"],
  },
  {
    id: "cert_excellence",
    name: "Excellence Certificate",
    subtitle: "Outstanding Performance",
    description: "Awarded for achieving an average score of 80%+ across 10+ assessments.",
    condition: (s) => s.avgScore >= 80 && s.totalAssessments >= 10,
    progressDesc: (s) => {
      const parts = [];
      if (s.avgScore < 80) parts.push(`Avg score ${s.avgScore}% → 80%`);
      if (s.totalAssessments < 10) parts.push(`${10 - s.totalAssessments} more assessments`);
      return parts.length ? `Need: ${parts.join(" & ")}` : "Earned!";
    },
    color: "#D97706",
    gradient: "linear-gradient(135deg, #D97706 0%, #92400E 100%)",
    emoji: "⭐",
    requiredBadges: ["avg_80", "assessments_10"],
  },
  {
    id: "cert_master",
    name: "Master Learner",
    subtitle: "Knowledge & Mastery",
    description: "Awarded for completing 25+ assessments while maintaining 70%+ average.",
    condition: (s) => s.totalAssessments >= 25 && s.avgScore >= 70,
    progressDesc: (s) => {
      const parts = [];
      if (s.totalAssessments < 25) parts.push(`${25 - s.totalAssessments} more assessments`);
      if (s.avgScore < 70) parts.push(`Avg score ${s.avgScore}% → 70%`);
      return parts.length ? `Need: ${parts.join(" & ")}` : "Earned!";
    },
    color: "#C4952A",
    gradient: "linear-gradient(135deg, #C4952A 0%, #92400E 100%)",
    emoji: "👑",
    requiredBadges: ["assessments_25", "avg_80"],
  },
];

export function computeAchievementStats(dashData) {
  if (!dashData) return null;
  const { stats, analytics } = dashData;
  const totalAssessments = stats?.assessments?.value ?? 0;
  const avgScore = stats?.overallProgress?.value ?? 0;
  const currentStreak = stats?.learningStreak?.value ?? 0;
  const activeDays = analytics?.streak?.activeDays ?? 0;
  const history = analytics?.assessments?.history ?? [];
  const highestScore = analytics?.assessments?.highestScore ?? 0;
  const hasPerfectScore = highestScore === 100;
  const skillsImproved = analytics?.skills?.improved ?? [];
  const maxImprovement = skillsImproved.length > 0
    ? Math.max(...skillsImproved.map((s) => s.improvement)) : 0;
  const totalQuestions = history.reduce((sum, h) => sum + (h.totalQuestions || 0), 0);
  return { totalAssessments, avgScore, currentStreak, activeDays, hasPerfectScore, maxImprovement, totalQuestions, highestScore };
}
