import React from "react";
import { Link } from "react-router-dom";

export default function RoadmapSection({ roadmap }) {
  // roadmap.phases is an array. we just flatten the steps to get the first 5 steps.
  let steps = [];
  if (roadmap?.phases) {
    for (const phase of roadmap.phases) {
      if (phase.steps) {
        steps.push(...phase.steps);
      }
    }
  }

  const items = steps.slice(0, 5);
  
  if (items.length === 0) {
    return (
      <div className="rounded-2xl bg-[#FBF8F0] p-6 sm:p-8 border border-[#2E4F42]/12 shadow-[var(--shadow-card)]">
        <h2 className="font-sans text-xl font-bold text-[#1B332C]">YOUR LEARNING ROADMAP</h2>
        <p className="text-sm text-[#5B6B5F] mt-2 mb-4">Complete an assessment to generate your personalized AI learning roadmap.</p>
        <Link to="/roadmap" className="inline-block px-4 py-2 bg-[#1B332C] text-[#E8C547] rounded-lg text-sm font-semibold hover:bg-[#2E4F42]">View Roadmap</Link>
      </div>
    );
  }

  const getStatusMeta = (status) => {
    switch (status) {
      case "COMPLETED":
        return {
          icon: "✓",
          label: "Completed",
          circleBg: "bg-[#2E4F42] text-[#FBF8F0] border-[#2E4F42]",
          cardBg: "bg-[#FBF8F0] border-[#2E4F42]/15 text-[#1B332C] hover:border-[#2E4F42] hover:bg-[#2E4F42]/05",
          textColor: "text-[#2E4F42]",
        };
      case "IN_PROGRESS":
        return {
          icon: "▶",
          label: "In Progress",
          circleBg: "bg-[#D9A62B] text-[#1B332C] border-[#B9860F] ring-4 ring-[#E8C547]/30",
          cardBg: "bg-[#1B332C] text-[#FBF8F0] border-[#C4952A] shadow-md hover:scale-[1.02] hover:shadow-[var(--shadow-card-hover)]",
          textColor: "text-[#E8C547]",
        };
      case "NOT_STARTED":
      default:
        return {
          icon: "🔒",
          label: "Upcoming",
          circleBg: "bg-[#EDE6D3] text-[#5B6B5F] border-[#2E4F42]/20",
          cardBg: "bg-[#FBF8F0]/60 border-[#2E4F42]/10 text-[#8B9690] hover:border-[#2E4F42]/30 hover:bg-[#EDE6D3]/70 hover:text-[#1B332C]",
          textColor: "text-[#8B9690]",
        };
    }
  };

  return (
    <div className="rounded-2xl bg-[#FBF8F0] p-6 sm:p-8 border border-[#2E4F42]/12 shadow-[var(--shadow-card)] hover:shadow-[var(--shadow-card-hover)] transition-all duration-300 flex flex-col gap-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="font-sans text-xl sm:text-2xl font-bold text-[#1B332C]">
            {roadmap?.roadmapTitle || "YOUR LEARNING ROADMAP"}
          </h2>
          <p className="text-xs sm:text-sm text-[#5B6B5F] font-normal mt-0.5">
            {roadmap?.summary ? roadmap.summary.substring(0, 80) + '...' : "Structured milestone pathway generated by AI."}
          </p>
        </div>

        <Link
          to="/roadmap"
          className="inline-flex items-center justify-center gap-2 rounded-xl font-semibold transition-all duration-200 bg-[#1B332C] text-[#E8C547] hover:bg-[#2E4F42] hover:text-white px-4 py-2 text-xs shadow-xs hover:scale-105 transition-transform shrink-0"
        >
          View Full AI Roadmap →
        </Link>
      </div>

      <div className="relative mt-1">
        <div className="grid grid-cols-1 sm:grid-cols-5 gap-4">
          {items.map((item, idx) => {
            const meta = getStatusMeta(item.completionStatus);
            const isLast = idx === items.length - 1;

            return (
              <div key={item.id || item.skillId || item._id || idx} className="relative flex flex-col gap-3 group cursor-pointer">
                {!isLast && (
                  <div className="hidden sm:block absolute top-4 left-1/2 w-full h-0.5 bg-[#2E4F42]/20 -z-0">
                    <div
                      className={`h-full transition-all duration-300 ${
                        item.completionStatus === "COMPLETED" ? "bg-[#2E4F42]" : "bg-transparent"
                      }`}
                    />
                  </div>
                )}
                <div className="relative z-10 flex items-center justify-start sm:justify-center">
                  <div
                    className={`flex h-9 w-9 items-center justify-center rounded-full font-mono font-bold text-sm border transition-transform duration-200 group-hover:scale-110 shadow-2xs ${meta.circleBg}`}
                  >
                    {meta.icon}
                  </div>
                </div>
                <div
                  className={`rounded-xl p-4 border transition-all duration-200 ${meta.cardBg}`}
                >
                  <span className="font-mono text-[10px] uppercase tracking-wider font-bold block mb-1 opacity-80">
                    Priority: {item.priority}
                  </span>
                  <h4 className="font-sans text-sm sm:text-base font-bold leading-tight">
                    {item.topic}
                  </h4>
                  <span
                    className={`inline-block font-mono text-xs font-semibold mt-2 ${meta.textColor}`}
                  >
                    {meta.label}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
